// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: proto/purchase/purchase.proto

package purchase

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckPurchaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tourId,proto3" json:"tourId,omitempty"`
	TouristId     int64                  `protobuf:"varint,2,opt,name=touristId,proto3" json:"touristId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPurchaseRequest) Reset() {
	*x = CheckPurchaseRequest{}
	mi := &file_proto_purchase_purchase_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPurchaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPurchaseRequest) ProtoMessage() {}

func (x *CheckPurchaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_purchase_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPurchaseRequest.ProtoReflect.Descriptor instead.
func (*CheckPurchaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_purchase_purchase_proto_rawDescGZIP(), []int{0}
}

func (x *CheckPurchaseRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *CheckPurchaseRequest) GetTouristId() int64 {
	if x != nil {
		return x.TouristId
	}
	return 0
}

type CheckPurchaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Purchased     bool                   `protobuf:"varint,1,opt,name=purchased,proto3" json:"purchased,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPurchaseResponse) Reset() {
	*x = CheckPurchaseResponse{}
	mi := &file_proto_purchase_purchase_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPurchaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPurchaseResponse) ProtoMessage() {}

func (x *CheckPurchaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_purchase_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPurchaseResponse.ProtoReflect.Descriptor instead.
func (*CheckPurchaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_purchase_purchase_proto_rawDescGZIP(), []int{1}
}

func (x *CheckPurchaseResponse) GetPurchased() bool {
	if x != nil {
		return x.Purchased
	}
	return false
}

var File_proto_purchase_purchase_proto protoreflect.FileDescriptor

const file_proto_purchase_purchase_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/purchase/purchase.proto\x12\bpurchase\"L\n" +
	"\x14CheckPurchaseRequest\x12\x16\n" +
	"\x06tourId\x18\x01 \x01(\tR\x06tourId\x12\x1c\n" +
	"\ttouristId\x18\x02 \x01(\x03R\ttouristId\"5\n" +
	"\x15CheckPurchaseResponse\x12\x1c\n" +
	"\tpurchased\x18\x01 \x01(\bR\tpurchased2c\n" +
	"\x0fPurchaseService\x12P\n" +
	"\rCheckPurchase\x12\x1e.purchase.CheckPurchaseRequest\x1a\x1f.purchase.CheckPurchaseResponseB\x1cZ\x1asoaprojekat/proto/purchaseb\x06proto3"

var (
	file_proto_purchase_purchase_proto_rawDescOnce sync.Once
	file_proto_purchase_purchase_proto_rawDescData []byte
)

func file_proto_purchase_purchase_proto_rawDescGZIP() []byte {
	file_proto_purchase_purchase_proto_rawDescOnce.Do(func() {
		file_proto_purchase_purchase_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_purchase_purchase_proto_rawDesc), len(file_proto_purchase_purchase_proto_rawDesc)))
	})
	return file_proto_purchase_purchase_proto_rawDescData
}

var file_proto_purchase_purchase_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_purchase_purchase_proto_goTypes = []any{
	(*CheckPurchaseRequest)(nil),  // 0: purchase.CheckPurchaseRequest
	(*CheckPurchaseResponse)(nil), // 1: purchase.CheckPurchaseResponse
}
var file_proto_purchase_purchase_proto_depIdxs = []int32{
	0, // 0: purchase.PurchaseService.CheckPurchase:input_type -> purchase.CheckPurchaseRequest
	1, // 1: purchase.PurchaseService.CheckPurchase:output_type -> purchase.CheckPurchaseResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_purchase_purchase_proto_init() }
func file_proto_purchase_purchase_proto_init() {
	if File_proto_purchase_purchase_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_purchase_purchase_proto_rawDesc), len(file_proto_purchase_purchase_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_purchase_purchase_proto_goTypes,
		DependencyIndexes: file_proto_purchase_purchase_proto_depIdxs,
		MessageInfos:      file_proto_purchase_purchase_proto_msgTypes,
	}.Build()
	File_proto_purchase_purchase_proto = out.File
	file_proto_purchase_purchase_proto_goTypes = nil
	file_proto_purchase_purchase_proto_depIdxs = nil
}
